version: "3"

services:
  db-postgres-marmitech:
    image: postgres:alpine
    ports:
      - "5435:5432"
    container_name: "db-postgres-marmitech"
    restart: always
    volumes:
      - ./db-marmitech-api:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    
volumes:
  db-marmitech-api:
      
    